fix pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,4 +3,10 @@
 echo "testing now..."
 echo "========================================"
 CI=true make test
+
+if [ $? -ne 0 ]; then
+  echo "Tests failed, aborting commit"
+  exit 1
+fi
+
 echo "========================================"
